apiVersion: apps/v1
kind: Deployment
metadata:
  name: haigpt
spec:
  selector:
    matchLabels:
      app: haigpt
  replicas: 3
  template:
    metadata:
      labels:
        app: haigpt
    spec:
      containers:
        - name: haigpt
          image: $(IMAGE)